### PR TITLE
Enhanced Contributing guidelines

### PR DESCRIPTION
**Pull request by Arcturus22**
# Description

Revised the contributing.md document for improved clarity and structure, thus making it easily understandable for the users.

### CODE REVIEW

**Comment by Arcturus22** [comment]
@FreddyDevelop  @bjoern-m @lfleischmann 
Please review the Pull Request and if the changes are according to your liking, kindly merge them.

**Comment by Arcturus22** [comment]
@lfleischmann @bjoern-m @FreddyDevelop 
Please review this PR and suggest changes (if any)

**Comment by Arcturus22** [comment]
@lfleischmann @bjoern-m @FreddyDevelop @FlxMgdnz 
Please review this PR and suggest changes (if any)

**Comment by FlxMgdnz** [comment]
Thanks, we don't see any value in this PR. Please don't spam.

**Pull request closed without merging**
