### PR TITLE
Added JWT-Python-APP snippet

### PR DESCRIPTION
**Pull request by MAYANK-TRIPATH**
/claim #975
Added JWT python app snippet example.

### CODE REVIEW

**Comment by MAYANK-TRIPATH** [comment]
@FlxMgdnz Please look into it, i guess it works fine.

**Comment by FlxMgdnz** [comment]
Thank you for this. Did you actually test the code?

**Comment by MAYANK-TRIPATH** [comment]
I couldn't fully test the code due to the absence of a real API URL.
For method issues part using methods from the jose library (jwt and jwk), the requests library, and the Flask framework.

**Comment by FlxMgdnz** [comment]
You can get a real API URL at cloud.hanko.io for free. Would be great if you could verify that everything works before we include the code in our docs.

**Comment by MAYANK-TRIPATH** [comment]
Thanks for API URL !
Updated with new example and tested to works fine :)

**Comment by FlxMgdnz** [comment]
Could you please provide the example as well so we can test it?

**Comment by MAYANK-TRIPATH** [comment]
I am using this example :-
```
from flask import Flask, request, jsonify
import jwt
import requests

app = Flask(__name__)

# Replace with your Hanko API URL
HANKO_API_URL = "https://your-hanko-api-url.com"

@app.route('/protected', methods=['GET'])
def protected_route():
    auth_header = request.headers.get('Authorization')

    if not auth_header or not auth_header.startswith('Bearer '):
        return jsonify({"message": "Missing or invalid token"}), 401

    token = auth_header.split(' ')[1]

    try:
        jwks_response = requests.get(f"{HANKO_API_URL}/.well-known/jwks.json")
        jwks_data = jwks_response.json()

        public_key = jwt.algorithms.RSAAlgorithm.from_jwk(jwks_data['keys'][0])
        
        payload = jwt.decode(
            token,
            public_key,
            algorithms=['RS256'],
            options={'verify_exp': True}
        )

        user_id = payload.get('sub')
        return jsonify({"message": f"Authenticated user: {user_id}"}), 200

    except Exception as e:
        return jsonify({"message": "Invalid token"}), 403

if __name__ == '__main__':
    app.run(debug=True)

``` 
for this you need to install some dependencies 
```
pip install flask jwt requests

``` 
And obviously in `HANKO_API_URL` place use real API.

**Comment by MAYANK-TRIPATH** [comment]
postman
Getting this response

**Comment by MAYANK-TRIPATH** [comment]
postman1
getting this response.

**Comment by MAYANK-TRIPATH** [comment]
Hey @FlxMgdnz Any update regarding this one?

**Comment by Ashutosh-Bhadauriya** [comment]
@MAYANK-TRIPATH Sorry we had a bit of a delay from our side. I see you have tested for the first case, that is when you don't have a valid jwt. Have you also tested by providing it a valid jwt? Thanks!

**Pull request closed without merging**
