### PR TITLE
docs: added the python backend guide

### LINKED ISSUE #980: FastAPI backend guide
We've received this middleware snipped for JWT handling in Python with FastAPI.

Check the code (does it work, can it be minimized?) and add it to docs/backend-guides if you approve.

```
from typing import Any

import jwt
from fastapi import FastAPI, Request
from fastapi.responses import JSONResponse

HANKO_API_URL = "XXX"


def deny():
    return JSONResponse(content={"error": "Unauthorized"}, status_code=401)


def extract_token_from_header(header: str):
    parts = header.split()

    if len(parts) != 2:
        return None

    scheme = parts[0].lower()
    token = parts[1]

    if scheme != "bearer":
        return None

    return token


app = FastAPI()


@app.middleware("http")
async def auth(request: Request, call_next: Any):
    authorization = request.headers.get("authorization")

    if not authorization:
        return deny()

    token = extract_token_from_header(authorization)

    if not token:
        return deny()

    jwks_client = jwt.PyJWKClient(HANKO_API_URL)
    signing_key = jwks_client.get_signing_key_from_jwt(token)
    data = jwt.decode(
        token,
        signing_key.key,
        algorithms=["RS256"],
        audience="localhost",
        options={"verify_exp": False},
    )

    if not data:
        return deny()

    return await call_next(request)
```

### PR DESCRIPTION
**Pull request by Chigala**
# Description
confirmed the backend guide is working, and updated the python backend guide. 

/closes #980 
/claim #980

### CODE REVIEW

**Comment by Chigala** [comment]
I was wrong, the code works.

**Comment by FlxMgdnz** [comment]
Hey @Chigala could you please provide the example app as well so we can test it?

**Comment by Chigala** [comment]
@FlxMgdnz  I'm very sorry for the delay, I just saw your comment like some minutes ago. Here is the example app. https://github.com/Chigala/hanko-fastapi-guide, you can add the necessary token and then run it. while testing I used the example Next project in the repo to get the cookie token, then the `HANKO_API_URL` was from my hanko dashboard. Everything works fine but for you to run it  in development, you will have to add this: 
```python
 # Disable SSL certificate verification
    ssl_context = ssl.create_default_context()
    ssl_context.check_hostname = False
    ssl_context.verify_mode = ssl.CERT_NONE

        jwks_client = jwt.PyJWKClient(
            HANKO_API_URL + "/.well-known/jwks.json", ssl_context=ssl_context
        )
```
Maybe I should have included this in the docs too, what do you think?

**Comment by Ashutosh-Bhadauriya** [comment]
@Chigala sorry we had a bit of a delay from our side. Everything looks good, we'll be merging soon.

> Maybe I should have included this in the docs too, what do you think?
Yes, please. Thanks!

**Comment by Chigala** [comment]
@Ashutosh-Bhadauriya @FlxMgdnz I just updated the docs. I think this can be merged now.

**Comment by Ashutosh-Bhadauriya** [comment]
Thanks @Chigala, we'll merge it soon

**Review by Ashutosh-Bhadauriya — APPROVED** [review]

**Pull request merged**
