### PR TITLE
feat: hanko bug finding tasks

### PR DESCRIPTION
**Pull request by adilkadivala**
# Description

Bug hunting

### Points

50 - 150 

### Description

only loads a component which is clicked

in login and create accont page 

when click on signup with google or github

then both are loads

### Provide proof that you've completed the task

hancobug2

hancobug

### CODE REVIEW

**Comment by FlxMgdnz** [comment]
Can you explain what you think the bug is? I don't understand the report, sorry.

**Comment by adilkadivala** [comment]
when I click on any one button then loading both ;;

If i click on google then loading google and github both, and same when I click on github

**Comment by adilkadivala** [comment]
hey @FlxMgdnz please check out my all side-quest ,  I have completes 6 ,  but just got 150 points

**Comment by adilkadivala** [comment]
my all side-quest [here](https://github.com/teamhanko/hanko/issues/created_by/@me)

**Pull request closed without merging**
