### PR TITLE
ossgg: X, Linkedin, Meme side quest

### PR DESCRIPTION
**Pull request by Yash-1511**
# Description

Completed Follow and post and meme on X about Hanko, followed on Linkedin. 

Screenshot 2024-10-11 165019

Yash Parmar headshot

### CODE REVIEW

**Comment by Yash-1511** [comment]
@FlxMgdnz I think you forgot to add 150 points for meme side quest!

**Comment by FlxMgdnz** [comment]
> @FlxMgdnz I think you forgot to add 150 points for meme side quest!

Right, sorry :)

**Pull request closed without merging**
